#!/bin/bash

echo "=========================================="
echo "3CUBED-SEO DATABASE UPDATE"
echo "=========================================="
echo ""
echo "This script will guide you through updating the database with AI-generated fields."
echo ""
echo "PROJECT REFERENCE: ktchrfgkbpaixbiwbieg"
echo ""
echo "OPTION 1: Run via Supabase Dashboard (Recommended)"
echo "-------------------------------------------------"
echo "1. Go to: https://app.supabase.com/project/ktchrfgkbpaixbiwbieg/sql"
echo "2. Click 'New Query'"
echo "3. Copy and paste the contents of:"
echo "   supabase/migrations/20250122_combined_ai_fields_update.sql"
echo "4. Click 'Run' to execute"
echo ""
echo "OPTION 2: Run via Supabase CLI"
echo "------------------------------"
echo "1. Login to Supabase CLI:"
echo "   npx supabase login"
echo ""
echo "2. Link the project:"
echo "   npx supabase link --project-ref ktchrfgkbpaixbiwbieg"
echo ""
echo "3. Run the migration:"
echo "   npx supabase db push"
echo ""
echo "WHAT THIS UPDATE ADDS:"
echo "----------------------"
echo "✓ seo_title field (AI-generated, 50-60 chars)"
echo "✓ geo_event_tags array (AI-generated conference tags)"
echo "✓ seo_strategy_outline (AI-generated SEO strategy)"
echo "✓ h2_tags array (AI-extracted H2 headings)"
echo "✓ Review tracking table"
echo "✓ GEO optimizations table"
echo "✓ Event tags lookup table with medical conferences"
echo ""
echo "After running the migration, verify by checking:"
echo "https://app.supabase.com/project/ktchrfgkbpaixbiwbieg/editor"
echo ""
